# Generated by Django 5.0.4 on 2024-07-18 08:19

import django.db.models.deletion
import utils.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рыбы')),
                ('description', models.TextField(verbose_name='Описание рыбки')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('restock_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishes', to='categories.fishcategory', verbose_name='Категории рыб')),
            ],
        ),
        migrations.CreateModel(
            name='FishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.image_path.fish_upload, verbose_name='Картинка рыбы')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_images', to='fish.fish', verbose_name='Рыба')),
            ],
            options={
                'verbose_name': 'Изображение Рыбы',
                'verbose_name_plural': 'Изображение Рыбы',
            },
        ),
    ]
