# Generated by Django 5.0.4 on 2024-07-19 06:48

import django.db.models.deletion
import utils.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
        migrations.CreateModel(
            name='AccessoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.image_path.accessories, verbose_name='Картинка аксессуара')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_images', to='accessories.accessory', verbose_name='Аксессуар')),
            ],
            options={
                'verbose_name': 'Изображение аксессуара',
                'verbose_name_plural': 'Изображение аксессуара',
            },
        ),
    ]
